nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000'] # Allow React's development server
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Authorization']
        max_age: 3600
    paths:
        '^/': ~ # Apply CORS rules to all endpoints
